CREATE TABLE Costs (
    Id INT PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    Department NVARCHAR(100) NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Currency NVARCHAR(10) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
